<?php

namespace AppBundle\Repository;

/**
 * OrderCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
