# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,                        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,                        role: ROLE_ADMIN }
        - { path: ^/,                              role: ROLE_USER }
        - { path: ^/customer/index,                role: ROLE_USER }
        - { path: ^/customer/create,               role: ROLE_USER }
        - { path: ^/customer/update,               role: ROLE_USER }
        - { path: ^/customer/delete,               role: ROLE_USER }
        - { path: ^/statistical/index,             role: ROLE_USER }
        - { path: ^/customers/index,               role: ROLE_USER }
        - { path: ^/customer/create,               role: ROLE_USER }
        - { path: ^/customer/sort,                 role: ROLE_USER }
        - { path: ^/customer/search,               role: ROLE_USER }
        - { path: ^/products/index,                role: ROLE_USER }
        - { path: ^/product/create,                role: ROLE_USER }
        - { path: ^/product/search,                role: ROLE_USER }
        - { path: /ordersCustomer/index,           role: ROLE_USER }
        - { path: /order/product/insert,           role: ROLE_USER }
        - { path: /order/product/update/price,     role: ROLE_USER }
        - { path: /order/product/update/quantity,  role: ROLE_USER }
        - { path: /order/product/delete,           role: ROLE_USER }
        - { path: /statistical/index,              role: ROLE_USER }
