<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \AppBundle\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'numberAccount', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'entitled', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'ranking', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'nameRepresentative', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'additionalAddress', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'zipCode', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'city', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'phoneNumber', 'price', 'user', 'createdAt', 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'numberAccount', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'entitled', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'ranking', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'nameRepresentative', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'additionalAddress', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'zipCode', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'city', '' . "\0" . 'AppBundle\\Entity\\Customer' . "\0" . 'phoneNumber', 'price', 'user', 'createdAt', 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberAccount($numberAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberAccount', [$numberAccount]);

        return parent::setNumberAccount($numberAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberAccount', []);

        return parent::getNumberAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntitled($entitled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntitled', [$entitled]);

        return parent::setEntitled($entitled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntitled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntitled', []);

        return parent::getEntitled();
    }

    /**
     * {@inheritDoc}
     */
    public function setRanking($ranking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRanking', [$ranking]);

        return parent::setRanking($ranking);
    }

    /**
     * {@inheritDoc}
     */
    public function getRanking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRanking', []);

        return parent::getRanking();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameRepresentative($nameRepresentative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameRepresentative', [$nameRepresentative]);

        return parent::setNameRepresentative($nameRepresentative);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameRepresentative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameRepresentative', []);

        return parent::getNameRepresentative();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdditionalAddress($additionalAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdditionalAddress', [$additionalAddress]);

        return parent::setAdditionalAddress($additionalAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdditionalAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdditionalAddress', []);

        return parent::getAdditionalAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($date = 'now')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$date]);

        return parent::setCreatedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$date]);

        return parent::setUpdatedAt($date);
    }

}
